algo = input('Digite algo:')
print('O tipo da classe é {}'.format(type(algo)))
print('É alfanumérico? {}'.format(algo.isalnum()))
print('É Alfabetico? {}'.format(algo.isalpha()))
print('É numérico? {}'.format(algo.isnumeric()))
print('É maiúsculo? {}'.format(algo.isupper()))
print('Está em maiúsculo? {}'.format(algo.isupper()))
print('Está em minúsculo? {}'.format(algo.islower()))
print('Está Capitalizado? {}'.format(algo.istitle()))
